model: CoSSL
model_args:
    topK: 5
    cap_Q: 1024
    dim: 256
out_dir: experiment/
audio_h5: ../features/woz_raw.h5
ref_h5: ../features/woz_emoji.h5
trainloader_args:
    batch_size: 16
    num_workers: 4
    shuffle: True
devloader_args:
    batch_size: 4
    num_workers: 4
    shuffle: False
optimizer: Adam
optimizer_args:
    lr: 0.0002
scheduler: ReduceLROnPlateau
scheduler_args:
        mode: min
        factor: 0.9
        patience: 3
        cooldown: 1
        verbose: False
        threshold: 0.001
criterion: WeightedMultiNCELoss
criterion_args: {}
save_interval: 10
patience: 20
n_epochs: 100
augment_p: 0.5
