model: ReCLR
switch_hard: 5
model_args:
    momentum: 0.999
    topK: 5
    cap_Q: 2048
    audio_dim: 256
    ref_dim: 512
    out_dim: 256
out_dir: experiment/iemocap/
audio_h5: mdd_raw.hdf5
ref_h5: mdd_iemocap.hdf5
trainloader_args:
    batch_size: 256
    num_workers: 4
    shuffle: True
devloader_args:
    batch_size: 64
    num_workers: 4
    shuffle: True
optimizer: Adam
optimizer_args:
    lr: 0.00001
scheduler: ReduceLROnPlateau
scheduler_args:
        mode: min
        factor: 0.5
        patience: 2
        cooldown: 1
        verbose: False
        threshold: 0.01
criterion: WeightedMultiNCELoss
criterion_args: 
    lambd: 0.8
save_interval: 5
patience: 10
n_epochs: 30
audio_args:
    p: 0.8
    output: lms
    spec_aug: True
    sr: 22050
