model: CoSSL
switch_hard: 20
model_args:
    topK: 5
    cap_Q: 512
    dim: 1280
out_dir: experiment/
audio_h5: ../features/woz_raw.h5
ref_h5: ../features/woz_emoji.h5
trainloader_args:
    batch_size: 32
    num_workers: 8
    shuffle: True
devloader_args:
    batch_size: 32
    num_workers: 4
    shuffle: True
optimizer: Adam
optimizer_args:
    lr: 0.004
scheduler: ReduceLROnPlateau
scheduler_args:
        mode: min
        factor: 0.9
        patience: 3
        cooldown: 1
        verbose: False
        threshold: 0.001
criterion: WeightedMultiNCELoss
criterion_args: {}
save_interval: 10
patience: 40
n_epochs: 100
audio_args:
    p: 0.5
    type: lms
